let chengyu = [
  ['爱不释手', 'ài bù shì shǒu', 'love something too much to part with it'],
  ['爱屋及乌', 'ài wū jí wū', 'love me, love my dog'],
  ['按部就班', 'àn bù jiù bān', 'step-by-step / doing things in logical order'],
  ['百年树人', 'bǎi nián shù rén', 'it takes ten years to nurture a tree, but a hundred years to train a man'],
  ['百折不挠', 'bǎi zhé bù náo', 'to keep on fighting in spite of all setbacks'],
  ['班门弄斧', 'bān mén nòng fǔ', "display one's skills before an expert"],
  ['包罗万象', 'bāo luó wàn xiàng', 'all-inclusive'],
  ['闭门造车', 'bì mén zào chē', 'work behind closed doors'],
  ['变本加厉', 'biàn běn jiā lì', 'to become more intense'],
  ['标新立异', 'biāo xīn lì yì', 'to start on something new and different'],
  ['别出心裁', 'bié chū xīn cái', 'to adopt an original approach'],
  ['宾至如归', 'bīn zhì rú guī', 'guests feel at home'],
  ['不耻下问', 'bù chǐ xià wèn', "to not feel ashamed to ask and learn from one's subordinates"],
  ['不攻自破', 'bù gōng zì pò', '(of rumours, gossip etc.) collapse by itself'],
  ['不可救药', 'bù kě jiù yào', "beyond cure"],
  ['不可思议', 'bù kě sī yì', 'unimaginable'],
  ['不劳而获', 'bù láo ér huò', 'to reap without sowing'],
  ['不务正业', 'bù wù zhèng yè', "not to engage in honest work"],
  ['不省人事', 'bù shěng rén shì', 'to lose consciousness'],
  ['不遗余力', 'bù yí yú lì', 'to spare no pains or effort'],
  ['不翼而飞', 'bù yì ér fēi', 'to disappear without a trace'],
  ['不择手段', 'bù zé shǒu duàn', 'by hook or by crook'],
  ['不自量力', 'bù zì liàng lì', 'to be overconfident'],
  ['长年累月', 'cháng nián lèi yuè', 'year in, year out'],
  ['趁火打劫', 'chèn huǒ dǎ jié', "to profit from someone's misfortune"],
  ['重蹈覆辙', 'zhòng dào fù chè', 'to follow the track of an overturned cart / to repeat a disastrous policy'],
  ['愁眉不展', 'chóu méi bù zhǎn', 'with a worried frown'],
  ['出类拔萃', 'chū lèi bá cuì', 'outstanding'],
  ['川流不息', 'chuān liú bù xī', 'the stream flows without stopping'],
  ['吹毛求疵', 'chuī máo qiú cī', 'to nitpick'],
  ['垂涎三尺', 'chuí xián sān chǐ', 'drool with envy'],
  ['唇亡齿寒', 'chún wáng chǐ hán', 'interdependence of two neighbouring states'],
  ['从容不迫', 'cóng róng bù pò', "take one's time"],
  ['从善如流', 'cóng shàn rú liú', "willing to accept other people's views"],
  ['措手不及', 'cuo shǒu bù jí', 'caught off guard'],
  ['打草惊蛇', 'dǎ cǎo jīng shé', 'to act rashly and alert the enemy'],
  ['大刀阔斧', 'dà dāo kuo fǔ', 'bold and decisive'],
  ['大公无私', 'dà gōng wú sī', 'to be selfless'],
  ['大言不惭', 'dà yán bù cán', 'to boast shamelessly'],
  ['当机立断', 'dāng jī lì duàn', 'to make prompt decisions'],
  ['道听途说', 'dào tīng tú shuō', 'hearsay'],
  ['得寸进尺', 'dé cùn jìn chǐ', "give him an inch, and he'll want a mile"],
  ['得过且过', 'dé guo qiě guò', 'satisfied just to get through'],
  ['得意忘形', 'dé yì wàng xíng', 'beside oneself with joy'],
  ['德高望重', 'dé gāo wàng zhòng', 'a person of virtue and prestige'],
  ['对牛弹琴', 'duì niú tàn qín', 'offering a treat to an unappreciative audience'],
  ['耳濡目染', 'ěr rú mù rǎn', 'be influenced by what one constantly sees and hears'],
  ['发扬光大', 'fā yáng guāng dà', 'to develop and promote'],
  ['废寝忘食', 'fèi qǐn wàng shí', "to skip one's sleep and meals"],
  ['奋不顾身', 'fèn bù gù shēn', "undaunted by dangers"],
  ['风驰电掣', 'fēng chí diàn chè', 'fast as lightning'],
  ['奉公守法', 'fèng gōng shǒu fǎ', 'law-abiding'],
  ['凤毛麟角', 'fèng máo lín jiǎo', 'extremely rare'],
  ['敷衍塞责', 'fū yǎn sāi zé', "to skimp on the job"],
  ['改过自新', 'gǎi guò zì xīn', 'start with a clean slate'],
  ['高瞻远瞩', 'gāo zhān yuǎn zhǔ', 'show great foresight'],
  ['高枕无忧', 'gāo zhěn wú yōu', 'to sleep peacefully'],
  ['隔岸观火', 'gé àn guān huǒ', 'to look at trouble with indifference'],
  ['各有千秋', 'gè yǒu qiān qiū', 'each has its own merits'],
  ['根深蒂固', 'gēn shēn dì gù', 'deep-rooted (problem, etc.)'],
  ['功亏一篑', 'gōng kuī yī kuì', 'to fail through lack of a final effort'],
  ['勾心斗角', 'gōu xīn dòu jiǎo', 'to fight and scheme against each other'],
  ['苟且偷安', 'gǒu qiě tōu ān', 'making no attempt to improve oneself'],
  ['孤陋寡闻', 'gū lòu guǎ wén', 'ignorant and ill-informed'],
  ['孤掌难鸣', 'gū zhǎng nán míng', "it's difficult to achieve anything without support"],
  ['孤注一掷', 'gū zhù yī zhí', "put all your eggs in one basket"],
  ['沽名钓誉', 'gū míng diào yù', 'to fish for compliments'],
  ['古色古香', 'gǔ sè gǔ xiāng', '(ancient objects) interesting and appealing'],
  ['拐弯抹角', 'guǎi wān mǒ jiǎo', 'to beat about the bush'],
  ['光明正大', 'guāng míng zhèng dà', 'just and honorable'],
  ['光明磊落', 'guāng míng lěi luo', 'on the up-and-up'],
  ['海底捞针', 'hǎi dǐ lāo zhēn', 'to find a needle in a haystack'],
  ['含辛茹苦', 'hán xīn rú kǔ', 'endure all kinds of hardships'],
  ['好高骛远', 'hǎo gāo wù yuǎn', "to bite off more than one can chew"],
  ['好逸恶劳', 'hǎo yì è láo', 'detest work'],
  ['狐假虎威', 'hú jiǎ hǔ wēi', "to use powerful connections to intimidate people"],
  ['胡思乱想', 'hú sī luàn xiǎng', "to let one's imagination run wild"],
  ['胡作非为', 'hú zuò fēi wèi', 'to run amok'],
  ['花言巧语', 'huā yán qiǎo yǔ', 'elegant but insincere words'],
  ['画龙点睛', 'huà lóng diǎn jīng', 'to add the finishing touch'],
  ['画蛇添足', 'huà shé tiān zú', 'to overdo it'],
  ['挥金如土', 'huī jīn rú tǔ', 'to spend money like water'],
  ['混水摸鱼', 'hǔn shuǐ mō yú', 'to take advantage of a crisis for personal gain'],
  ['鸡犬不宁', 'jī quǎn bù zhù', 'utter confusion'],
  ['集思广益', 'jí sī guǎng yì', 'collecting opinions is of wide benefit'],
  ['家喻户晓', 'jiā yù hù xiǎo', 'well known'],
  ['假公济私', 'jiǎ gōng jì sī', 'official authority used for private interests'],
  ['见利忘义', 'jiàn lì wàng yì', "to sell one's soul for gain"],
  ['见异思迁', 'jiàn yì sī qiān', 'to change at once when seeing something different'],
  ['见义勇为', 'jiàn yì yǒng wèi', 'to stand up bravely for the truth'],
  ['捷足先登', 'jié zú xiān dēng', 'the early bird cathes the worm'],
  ['进退两难', 'jìn tuì liǎng nán', 'trapped / in an impossible situation'],
  ['进退维谷', 'jìn tuì wéi gǔ', 'trapped / in an impossible situation'],
  ['精益求精', 'jīng yì qiú jīng', 'to perfect something that is already outstanding'],
  ['居安思危', 'jū ān sī wēi', 'to be prepared for danger in times of safety'],
  ['井井有条', 'jǐng jǐng yǒu tiáo', 'neat and tidy'],
  ['鞠躬尽瘁', 'jú gōng jìn cuì', "spare no effort for a task"],
  ['举一反三', 'jǔ yī fǎn sān', 'to deduce many things from one case'],
  ['举足轻重', 'jǔ zú qīng zhòng', 'to play a decisive role'],
  ['开门见山', 'kāi mén jiàn shān', 'to get right to the point'],
  ['开源节流', 'kāi yuán jié liú', 'to increase income and save on spending'],
  ['慷慨解囊', 'kāng kǎi jiě náng', 'to contribute generously'],
  ['刻苦耐劳', 'kè kǔ nài láo', 'hard-working'],
  ['口是心非', 'kǒu shì xīn fēi', 'say one thing and mean another'],
  ['苦口婆心', 'kǔ kǒu pó xīn', 'earnest and well-meaning advice'],
  ['脍炙人口', 'kuài zhì rén kǒu', 'appealing to the masses'],
  ['滥竽充数', 'làn yú chōng shù', '(said of incompetent people or inferior goods) be there just to make up the number'],
  ['老马识途', 'lǎo mǎ shì tú', 'an experienced worker knows what to do'],
  ['理直气壮', 'lǐ zhí qì zhuàng', "bold and confident with justice on one's side"],
  ['力不从心', 'lì bù cóng xīn', "not as strong as one would wish"],
  ['励精图治', 'lì jīng tú zhì', 'make every effort to make the country prosperous'],
  ['瞭如指掌', 'liǎo rú zhǐ zhǎng', "to know something like the palm of one's hand"],
  ['临渴掘井', 'lín kě jué jǐng', 'to be unprepared and seek help at the last minute'],
  ['流离失所', 'liú lí shī suǒ', 'become destitute and homeless'],
  ['路不拾遗', 'lù bù shí yí', 'honesty prevails throughout society'],
  ['落花流水', 'luò huā liú shuǐ', 'to be in a sorry state'],
  ['络绎不绝', 'luò yì bù jué', 'continuously / in an endless stream'],
  ['满载而归', 'mǎn zài ér guī', 'to return from a rewarding journey'],
  ['慢条斯理', 'màn tiáo sī lǐ', 'slow and deliberate'],
  ['毛遂自荐', 'máo suì zì jiàn', "to volunteer one's services"],
  ['每况愈下', 'měi kuàng yù xià', 'go down the drain steadily deteriorate'],
  ['每下愈况', 'měi xià yù kuàng', 'steadily deteriorate'],
  ['面目全非', 'miàn mù quán fēi', 'to be changed beyond recognition'],
  ['明目张胆', 'míng mù zhāng dǎn', 'openly and without fear'],
  ['明哲保身', 'míng zhé bǎo shēn', "to put one's own safety before matters of principle"],
  ['明知故犯', 'míng zhī gù fàn', 'intentional crime'],
  ['目中无人', 'mù zhōng wú rén', 'to consider everyone else beneath one'],
  ['破釜沉舟', 'pò fǔ chén zhōu', "burn one's bridge"],
  ['普天同庆', 'pǔ tiān tóng qìng', 'everybody celebrating together'],
  ['杞人忧天', 'qǐ rén yōu tiān', 'have groundless worries'],
  ['千钧一发', 'qiān jūn yī fǎ', 'a thousand pounds hang by a thread'],
  ['千篇一律', 'qiān piān yī lǜ', "once you've seen one, you've seen them all"],
  ['千载难逢', 'qiān zài nán féng', 'once in a blue moon'],
  ['前车之鉴', 'qián chē zhī jiàn', "to learn a lesson from the mistakes of one's predecessor"],
  ['潜移默化', 'qián yí mò huà', 'to influence secretly'],
  ['强词夺理', 'qiáng cí duó lǐ', 'to twist words and force logic'],
  ['青出于蓝', 'qīng chū yú lán', 'the student surpasses his master'],
  ['倾家荡产', 'qīng jiā dàng chǎn', 'be reduced to poverty and ruin'],
  ['情同手足', 'qíng tóng shǒu zú', 'loving one another as brothers'],
  ['人浮于事', 'rén fú yú shì', 'overstaffed'],
  ['人云亦云', 'rén yún yì yún', 'to say what everyone says'],
  ['任劳任怨', 'rèn láo rèn yuàn', 'to undertake a task despite criticism'],
  ['荣华富贵', 'róng huá fù guì', 'glory, splendor, wealth and rank'],
  ['富贵荣华', 'fù guì róng huá', 'riches and honour'],
  ['如火如荼', 'rú huǒ rú tú', '(to spread) like a raging fire'],
  ['如释重负', 'rú shì zhòng fù', "to have a weight off one's mind"],
  ['三思而行', 'sān sī ér xíng', 'think twice before you act'],
  ['僧多粥少', 'sēng duō zhōu shǎo', 'not enough to satisfy everyone'],
  ['杀鸡取卵', 'shā jī qū luǎn', 'to kill the goose that lays the golden eggs'],
  ['舍己为人', 'shě jǐ wèi rén', 'to sacrifice oneself for the sake of others'],
  ['事半功倍', 'shì bàn gōng bèi', 'the right approach saves effort and leads to better results'],
  ['事倍功半', 'shì bèi gōng bàn', 'the right approach saves effort and leads to better results'],
  ['视死如归', 'shì sǐ rú guī', 'to not be afraid of dying'],
  ['手不释卷', 'shǒu bù shì juàn', 'to be very studious'],
  ['守口如瓶', 'shǒu kǒu rú píng', "tight-lipped"],
  ['守望相助', 'shǒu wàng xiāng zhù', 'help each other'],
  ['守株待兔', 'shǒu zhū dài tù', 'to wait idly for opportunities'],
  ['熟能生巧', 'shóu néng shēng qiǎo', 'practice makes perfect'],
  ['束手无策', 'shù shǒu wú cè', 'helpless in the face of a crisis'],
  ['水到渠成', 'shuǐ dào qú chéng', 'when conditions are right, success will follow naturally'],
  ['水落石出', 'shuǐ luo shí chū', 'the truth comes to light'],
  ['顺手牵羊', 'shùn shǒu qiān yáng', 'to steal something under cover of an emergency'],
  ['司空见惯', 'sī kōng jiàn guàn', 'a common occurrence'],
  ['似是而非', 'sì shì ér fēi', 'appeared right but was wrong'],
  ['随遇而安', 'suí yù ér ān', 'feel at ease under any circumstances'],
  ['滔滔不绝', 'tāo tāo bù jué', 'talking non-stop'],
  ['口若悬河', 'kǒu ruo xuán hé', 'eloquent'],
  ['提心吊胆', 'tí xīn diào dǎn', 'to be very scared and on edge'],
  ['挑拨离间', 'tiāo bō lí jiān', 'to drive a wedge between'],
  ['铤而走险', 'tǐng ér zǒu xiǎn', 'make a reckless move'],
  ['同甘共苦', 'tóng gān gòng kǔ', 'stick together through thick and thin'],
  ['同归于尽', 'tóng guī yú jìn', 'to take somebody down with oneself'],
  ['同流合污', 'tóng liú hé wū', 'to follow the bad example of others'],
  ['同舟共济', 'tóng zhōu gòng jì', "obliged to collaborate towards common goals"],
  ['投机取巧', 'tóu jī qū qiǎo', 'to seize every opportunity'],
  ['徒劳无功', 'tú láo wú gōng', "to work to no avail"],
  ['推陈出新', 'tuī chén chū xīn', 'to push out the old and bring in the new'],
  ['望尘莫及', 'wàng chén mo jí', 'too far behind to catch up with'],
  ['忘恩负义', 'wàng ēn fù yì', 'ungratefulness'],
  ['为非作歹', 'wèi fēi zuo dǎi', 'do evil'],
  ['未雨绸缪', 'wèi yǔ chóu móu', 'to plan ahead'],
  ['温故知新', 'wēn gù zhī xīn', 'understand the present by reviewing the past'],
  ['无病呻吟', 'wú bìng shēn yín', 'to moan about imaginary illness'],
  ['无动于衷', 'wú dòng yú zhōng', 'indifference'],
  ['无微不至', 'wú wēi bù zhì', 'very carefully and meticulously'],
  ['五体投地', 'wǔ tǐ tóu dì', "admire somebody from the bottom of one's heart"],
  ['息事宁人', 'xī shì zhù rén', 'make concessions to avoid trouble'],
  ['相安无事', 'xiāng ān wú shì', 'to live together in harmony'],
  ['相辅相成', 'xiāng fǔ xiāng chéng', 'to supplement each other'],
  ['心灰意懒', 'xīn huī yì lǎn', 'feel pessimistic and discouraged'],
  ['心旷神怡', 'xīn kuàng shén yí', 'be carefree and happy'],
  ['欣欣向荣', 'xīn xīn xiàng róng', 'flourishing / thriving'],
  ['信口开河', 'xìn kǒu kāi hé', 'to speak without thinking'],
  ['信口雌黄', 'xìn kǒu cí huáng', 'make irresponsible remarks'],
  ['兴高采烈', 'xīng gāo cǎi liè', 'in high spirits'],
  ['胸有成竹', 'xiōng yǒu chéng zhú', "have a card up one's sleeve"],
  ['袖手旁观', 'xiù shǒu páng guān', 'to look on without lifting a finger'],
  ['栩栩如生', 'xǔ xǔ rú shēng', 'lifelike'],
  ['悬崖勒马', 'xuán yá lè mǎ', 'to act in the nick of time'],
  ['削足适履', 'xuē zú shì lǚ', 'impractical or inelegant solution'],
  ['寻根究底', 'xún gēn jiù dǐ', 'get to the bottom of things'],
  ['循循善诱', 'xún xún shàn yòu', 'be good at teaching'],
  ['鸦雀无声', 'yā què wú shēng', 'absolute silence'],
  ['雅俗共赏', 'yǎ sú gòng shǎng', 'can be enjoyed by scholars and lay-people alike'],
  ['言行一致', 'yán xíng yī zhì', 'practice what you preach'],
  ['养尊处优', 'yǎng zūn chù yōu', 'to live like a prince'],
  ['摇摇欲坠', 'yáo yáo yù zhuì', 'on the verge of collapse'],
  ['一败涂地', 'yī bài tú dì', 'to fail utterly'],
  ['一帆风顺', 'yī fān fēng shùn', 'to go smoothly'],
  ['一见如故', 'yī jiàn rú gù', 'feel like old friends at the first meeting'],
  ['一举两得', 'yī jǔ liǎng dé', 'to kill two birds with one stone'],
  ['一箭双雕', 'yī jiàn shuāng diāo', 'to kill two birds with one stone'],
  ['一蹶不振', 'yī jué bù zhèn', 'unable to recover after a set-back'],
  ['一劳永逸', 'yī láo yǒng yì', 'to get something done once and for all'],
  ['一落千丈', 'yī luo qiān zhàng', 'to suffer a drastic decline'],
  ['一毛不拔', 'yī máo bù bá', 'stingy'],
  ['一暴十寒', 'yī bào shí hán', 'daily effort is needed learn and grow'],
  ['一视同仁', 'yī shì tóng rén', 'to treat everyone equally'],
  ['一事无成', 'yī shì wú chéng', 'to have achieved nothing'],
  ['一网打尽', 'yī wǎng dǎ jìn', 'to solve the problem in one swoop'],
  ['一意孤行', 'yī yì gū xíng', "insist on doing things in one's own way"],
  ['一针见血', 'yī zhēn jiàn xiě', 'to hit the nail on the head'],
  ['一知半解', 'yī zhī bàn jiě', 'have little knowledge and no comprehension'],
  ['以卵击石', 'yǐ luǎn jí shí', 'to attempt the impossible'],
  ['以身作则', 'yǐ shēn zuò zé', 'set a good example'],
  ['以牙还牙', 'yǐ yá huán yá', 'an eye for an eye'],
  ['易如反掌', 'yì rú fǎn zhǎng', "as easy as turning one's hand over"],
  ['异想天开', 'yì xiǎng tiān kāi', "to let one's imagination run wild"],
  ['饮水思源', 'yǐn shuǐ sī yuán', "be grateful for all your blessings"],
  ['迎刃而解', 'yíng rèn ér jiě', 'easily solved'],
  ['应接不暇', 'yìng jiē bù xiá', 'more business than one can attend to'],
  ['优柔寡断', 'yōu róu guǎ duàn', 'indecisive'],
  ['游手好闲', 'yóu shǒu hǎo xián', 'to idle about'],
  ['有目共睹', 'yǒu mù gòng dǔ', 'obvious to all'],
  ['有勇无谋', 'yǒu yǒng wú móu', 'foolhardiness'],
  ['与日俱增', 'yǔ rì jù zēng', 'to increase steadily'],
  ['再接再厉', 'zài jiē zài lì', 'make persistent efforts'],
  ['真知灼见', 'zhēn zhī zhuó jiàn', 'penetrating insight'],
  ['蒸蒸日上', 'zhēng zhēng rì shàng', 'becoming more prosperous with each passing day'],
  ['执迷不悟', 'zhí mí bù wù', 'hold on to errors or wrong beliefs'],
  ['趾高气扬', 'zhǐ gāo qì yáng', "arrogant"],
  ['纸上谈兵', 'zhǐ shàng tán bīng', 'armchair strategist'],
  ['志同道合', 'zhì tóng dào hé', 'like-minded'],
  ['置之不理', 'zhì zhī bù lǐ', "to pay no heed to"],
  ['忠言逆耳', 'zhōng yán nì ěr', 'the truth seldom sounds pleasant'],
  ['装聋作哑', 'zhuāng lóng zuò yā', 'to act deaf and dumb'],
  ['自暴自弃', 'zì bào zì qì', 'to give up and stop bothering'],
  ['自力更生', 'zì lì gèng shēng', "stand on one's own feet"],
  ['自投罗网', 'zì tóu luó wǎng', 'to walk right into the trap'],
  ['自相矛盾', 'zì xiāng máo dùn', 'to contradict oneself'],
  ['坐井观天', 'zuò jǐng guān tiān', 'ignorant and narrow-minded'],
  ['坐享其成', 'zuò xiǎng qí chéng', 'to reap where one has not sown'],
  ['脚踏实地', 'jiǎo tà shí dì', 'be earnest and down-to-earth'],
  ['九牛一毛', 'jiǔ niú yī máo', 'a drop in the ocean'],
  ['一无所有', 'yī wú suǒ yǒu', "to not have a thing to one's name"],
  ['一见钟情', 'yī jiàn zhōng qíng', "love at first sight"],
  ['自由自在', 'zì yóu zì zài', "carefree"],
  ['莫名其妙', 'mò míng qí miào', "something (that) is baffling"],
  ['半途而废', 'bàn tú ér fèi', "start doing something, only to give up halfway"],
  ['抛砖引玉', 'pāo zhuān yǐn yù', "tossing an idea out there in the hopes that other people will improve it"],
  ['豁然开朗', 'huò rán kāi lǎng', "everything becomes clear at once"],
  ['津津有味', 'jīn jīn yǒu wèi', "to do something with great interest"],
  ['理所当然', 'lǐ suǒ dāng rán', "proper and to be expected as a matter of course"],
  ['全力以赴', 'quán lì yǐ fù', "to give it your all"],
  ['心血来潮', 'xīn xuè lái cháo', "spur of the moment"],
  ['乱七八糟', 'luàn qī bā zāo', "something is a total mess"],
  ['不可思议', 'bù kě sī yì', "something is noteworthy or amazing in an unexpected way"],
  ['瞒天过海', 'mán tiān guò hǎi', "to achieve one's aim by underhanded means"],
  ['借刀杀人', 'jiè dāo shā rén', "to get somebody else to do one's dirty work"],
  ['声东击西', 'shēng dōng jī xī', "to misdirect"],
  ['无中生有', 'wú zhōng shēng yǒu', "to create something from nothing"],
  ['李代桃僵', 'lǐ dài táo jiāng', "to substitute one thing for another"],
  ['调虎离山', 'diào hǔ lí shān', "lure the enemy from his base"],
  ['釜底抽薪', 'fǔ dǐ chōu xīn', "to take drastic measures to deal with a situation"]
]
