let chengyu = [
  ['爱不释手', 'ài bù shì shǒu', 'fondle admiringly'],
  ['爱屋及乌', 'ài wū jí wū', 'love me, love my dog'],
  ['按部就班', 'àn bù jiù bān', 'step-by-step follow the prescribed order'],
  ['百年树人', 'bǎi nián shù rén', 'a community'],
  ['百折不挠', 'bǎi zhé bù náo', 'keep fighting in spite of all setbacks'],
  ['班门弄斧', 'bān mén nòng fǔ', "display one's slight skill before an expert"],
  ['半途而废', 'bàn tú ér fèi', 'give up halfway leave sth. unfinished'],
  ['包罗万象', 'bāo luó wàn xiàng', 'all-inclusive all-embracing'],
  ['闭门造车', 'bì mén zào chē', 'work behind closed doors'],
  ['变本加厉', 'biàn běn jiā lì', 'be further intensified'],
  ['标新立异', 'biāo xīn lì yì', 'do sth. unconventionally do sth. unorthodox'],
  ['别出心裁', 'bié chū xīn cái', 'adopt an original approach try to be different'],
  ['宾至如归', 'bīn zhì rú guī', 'guests feel at home'],
  ['不耻下问', 'bù chǐ xià wèn', "feel not ashamed to learn from one's subordinates"],
  ['不攻自破', 'bù gōng zì pò', 'collapse of itself'],
  ['不可救药', 'bù kě jiù yào', "can't be saved beyond redemption"],
  ['不可思议', 'bù kě sī yì', 'inconceivable unimaginable'],
  ['不劳而获', 'bù láo ér huò', 'reap without sowing'],
  ['不务正业', 'bù wù zhèng yè', "not attend to one's proper duties"],
  ['不省人事', 'bù shěng rén shì', 'be unconscious'],
  ['不遗余力', 'bù yí yú lì', 'spare no pains or effort'],
  ['不翼而飞', 'bù yì ér fēi', 'disappear without a trace'],
  ['不择手段', 'bù zé shǒu duàn', 'by any kind of means play hard'],
  ['不自量力', 'bù zì liàng lì', 'over-confident'],
  ['长年累月', 'cháng nián lèi yuè', 'over the years'],
  ['趁火打劫', 'chèn huǒ dǎ jié', 'loot a burning house'],
  ['重蹈覆辙', 'zhòng dào fù chè', 'follow the same old disastrous road'],
  ['愁眉不展', 'chóu méi bù zhǎn', 'with knitted brows'],
  ['出类拔萃', 'chū lèi bá cuì', 'fill the bill'],
  ['川流不息', 'chuān liú bù xī', 'the stream flows without stopping'],
  ['吹毛求疵', 'chuī máo qiú cī', 'find a quarrel in a straw criticize'],
  ['垂涎三尺', 'chuí xián sān chǐ', 'drool with envy'],
  ['唇亡齿寒', 'chún wáng chǐ hán', 'interdependence of two neighbouring states'],
  ['从容不迫', 'cóng róng bù pò', "take one's time go easy"],
  ['从善如流', 'cóng shàn rú liú', 'accept good advices'],
  ['措手不及', 'cuo shǒu bù jí', 'unaware unprepared'],
  ['打草惊蛇', 'dǎ cǎo jīng shé', 'act rashly and alert the enemy'],
  ['大刀阔斧', 'dà dāo kuo fǔ', 'bold and decisive drastic'],
  ['大公无私', 'dà gōng wú sī', 'just and fair selfless'],
  ['大言不惭', 'dà yán bù cán', 'fanfaronade rodomontade'],
  ['当机立断', 'dāng jī lì duàn', 'make a prompt decision'],
  ['道听途说', 'dào tīng tú shuō', 'hearsay'],
  ['得寸进尺', 'dé cùn jìn chǐ', 'given an inch, want a mile'],
  ['得过且过', 'dé guo qiě guò', 'drift along'],
  ['得意忘形', 'dé yì wàng xíng', 'bloat get dizzy with success'],
  ['德高望重', 'dé gāo wàng zhòng', 'sainted saintlike'],
  ['对牛弹琴', 'duì niú tàn qín', 'whistle jigs to a milestone cast pearls before swine'],
  ['耳濡目染', 'ěr rú mù rǎn', 'be influenced by what one constantly sees and hears'],
  ['发扬光大', 'fā yáng guāng dà', 'to develop, advocate, and promulgate'],
  ['废寝忘食', 'fèi qǐn wàng shí', 'forget food and sleep'],
  ['奋不顾身', 'fèn bù gù shēn', "dash ahead regardless of one's safety"],
  ['风驰电掣', 'fēng chí diàn chè', 'move at great speed'],
  ['奉公守法', 'fèng gōng shǒu fǎ', 'law-abiding'],
  ['凤毛麟角', 'fèng máo lín jiǎo', 'rarity'],
  ['敷衍塞责', 'fū yǎn sāi zé', "perform one's duty in a perfunctory manner"],
  ['改过自新', 'gǎi guò zì xīn', 'start with a clean slate'],
  ['高瞻远瞩', 'gāo zhān yuǎn zhǔ', 'show great foresight'],
  ['高枕无忧', 'gāo zhěn wú yōu', 'rest easy'],
  ['隔岸观火', 'gé àn guān huǒ', 'look on trouble with indifference'],
  ['各有千秋', 'gè yǒu qiān qiū', 'each has his strong point'],
  ['根深蒂固', 'gēn shēn dì gù', 'deep-rooted (problem, etc.)'],
  ['功亏一篑', 'gōng kuī yī kuì', 'fall short of success for want of a final effort'],
  ['勾心斗角', 'gōu xīn dòu jiǎo', 'intrigue against each other'],
  ['苟且偷安', 'gǒu qiě tōu ān', 'seek temporary ease'],
  ['孤陋寡闻', 'gū lòu guǎ wén', 'ignorant and ill-informed'],
  ['孤掌难鸣', 'gū zhǎng nán míng', "it's difficult to achieve anything without support"],
  ['孤注一掷', 'gū zhù yī zhí', "a long shot gamble put all one's eggs in one basket"],
  ['沽名钓誉', 'gū míng diào yù', 'fish for fame and compliment'],
  ['古色古香', 'gǔ sè gǔ xiāng', '(of ancient objects of art) having an old-fashioned and antique flavour'],
  ['拐弯抹角', 'guǎi wān mǒ jiǎo', 'talk in a roundabout way ambages'],
  ['光明正大', 'guāng míng zhèng dà', 'fairness'],
  ['光明磊落', 'guāng míng lěi luo', 'on the up-and-up'],
  ['海底捞针', 'hǎi dǐ lāo zhēn', 'look for a needle in the ocean'],
  ['含辛茹苦', 'hán xīn rú kǔ', 'endure all kinds of hardships'],
  ['好高骛远', 'hǎo gāo wù yuǎn', "reach for what is beyond one's grasp"],
  ['好逸恶劳', 'hǎo yì è láo', 'indolence'],
  ['和睦共处', 'hé mù gòng chù', 'got along with peaceful coexistence'],
  ['狐假虎威', 'hú jiǎ hǔ wēi', "bully people by flaunting one's powerful connections"],
  ['胡思乱想', 'hú sī luàn xiǎng', "let one's imagination run away have a bee in one's head"],
  ['胡作非为', 'hú zuò fēi wèi', 'act wildly against law and public opinion'],
  ['花言巧语', 'huā yán qiǎo yǔ', 'blandishments sweet words'],
  ['画龙点睛', 'huà lóng diǎn jīng', 'make the finishing point'],
  ['画蛇添足', 'huà shé tiān zú', 'to overdo it gild the lily'],
  ['挥金如土', 'huī jīn rú tǔ', 'spend money like water'],
  ['混水摸鱼', 'hǔn shuǐ mō yú', 'fish in troubled waters'],
  ['鸡犬不宁', 'jī quǎn bù zhù', 'utter confusion'],
  ['集思广益', 'jí sī guǎng yì', 'draw on the wisdom of the masses'],
  ['家喻户晓', 'jiā yù hù xiǎo', 'understood by every household widely known'],
  ['假公济私', 'jiǎ gōng jì sī', 'job jobbery'],
  ['见利忘义', 'jiàn lì wàng yì', 'treacherous'],
  ['见异思迁', 'jiàn yì sī qiān', 'change about'],
  ['见义勇为', 'jiàn yì yǒng wèi', 'do boldly what is righteous ready to help others for a just cause'],
  ['捷足先登', 'jié zú xiān dēng', 'the early bird cathes the worm'],
  ['津津有味', 'jīn jīn yǒu wèi', 'with gusto with great interest'],
  ['进退两难', 'jìn tuì liǎng nán', 'have a wolf by the ears up a tree dilemma'],
  ['进退维谷', 'jìn tuì wéi gǔ', 'between the devil and the deep sea between two fires'],
  ['精益求精', 'jīng yì qiú jīng', 'continually seeking perfection'],
  ['居安思危', 'jū ān sī wēi', 'be prepared for danger in times of safety'],
  ['井井有条', 'jǐng jǐng yǒu tiáo', 'in perfect order neat and tidy methodical'],
  ['鞠躬尽瘁', 'jú gōng jìn cuì', "spare no effort in the performance of one's duty"],
  ['举一反三', 'jǔ yī fǎn sān', 'draw inferences about other cases from one instance'],
  ['举足轻重', 'jǔ zú qīng zhòng', 'hold the balance'],
  ['开门见山', 'kāi mén jiàn shān', 'to get right to the point'],
  ['开源节流', 'kāi yuán jié liú', 'increase revenue and reduce expenditure'],
  ['慷慨解囊', 'kāng kǎi jiě náng', 'generosity'],
  ['刻苦耐劳', 'kè kǔ nài láo', 'hardworking'],
  ['口是心非', 'kǒu shì xīn fēi', 'duplicity'],
  ['苦口婆心', 'kǔ kǒu pó xīn', 'advise sb. in earnest'],
  ['脍炙人口', 'kuài zhì rén kǒu', 'win universal praise'],
  ['滥竽充数', 'làn yú chōng shù', 'be there just to make up the number'],
  ['老马识途', 'lǎo mǎ shì tú', 'an old hand is a good guide'],
  ['理直气壮', 'lǐ zhí qì zhuàng', 'one is assured and bold with justice'],
  ['力不从心', 'lì bù cóng xīn', "ability not equal to one's ambition"],
  ['励精图治', 'lì jīng tú zhì', 'use all efforts to make the country prosperous'],
  ['瞭如指掌', 'liǎo rú zhǐ zhǎng', "know sth. like the palm of one's hand"],
  ['临渴掘井', 'lín kě jué jǐng', 'not make timely preparations'],
  ['流离失所', 'liú lí shī suǒ', 'become destitute and homeless'],
  ['路不拾遗', 'lù bù shí yí', 'no one picks up and pockets anything lost on the road'],
  ['落花流水', 'luò huā liú shuǐ', 'utterly routed'],
  ['络绎不绝', 'luò yì bù jué', 'in an endless stream'],
  ['满载而归', 'mǎn zài ér guī', 'come back with fruitful results'],
  ['慢条斯理', 'màn tiáo sī lǐ', 'leisurely unhurriedly'],
  ['毛遂自荐', 'máo suì zì jiàn', "volunteer one's services"],
  ['每况愈下', 'měi kuàng yù xià', 'go down the drain steadily deteriorate'],
  ['每下愈况', 'měi xià yù kuàng', 'steadily deteriorate'],
  ['面目全非', 'miàn mù quán fēi', 'beyond recognition'],
  ['明目张胆', 'míng mù zhāng dǎn', 'brazenly do evil openly'],
  ['明哲保身', 'míng zhé bǎo shēn', 'be worldly wise and make oneself safe'],
  ['明知故犯', 'míng zhī gù fàn', 'violate knowingly'],
  ['墨守成规', 'mò shǒu chéng guī', 'routinism scholasticism'],
  ['目中无人', 'mù zhōng wú rén', 'be overweening be supercilious'],
  ['弄巧反拙', 'nòng qiǎo fǎn zhuó', 'to backfire'],
  ['破釜沉舟', 'pò fǔ chén zhōu', "burn one's boats burn one's bridge"],
  ['普天同庆', 'pǔ tiān tóng qìng', 'the whole world or nation joins in jubilation'],
  ['杞人忧天', 'qǐ rén yōu tiān', 'meet troubles halfway'],
  ['千钧一发', 'qiān jūn yī fǎ', 'close call hang by a thread'],
  ['千篇一律', 'qiān piān yī lǜ', 'stereotyped, following the same pattern'],
  ['千载难逢', 'qiān zài nán féng', 'occuring only once in a thousand years'],
  ['前车之鉴', 'qián chē zhī jiàn', "lessons drawn from others' mistakes"],
  ['潜移默化', 'qián yí mò huà', 'exert a subtle influence on'],
  ['强词夺理', 'qiáng cí duó lǐ', 'deception by trickery or sophistry'],
  ['青出于蓝', 'qīng chū yú lán', 'the students surpass the teacher'],
  ['倾家荡产', 'qīng jiā dàng chǎn', 'be reduced to poverty and ruin'],
  ['情同手足', 'qíng tóng shǒu zú', 'brotherly love'],
  ['人浮于事', 'rén fú yú shì', 'overstaffed'],
  ['人云亦云', 'rén yún yì yún', 'echo what other says'],
  ['任劳任怨', 'rèn láo rèn yuàn', 'willingly bear the burden of hard works'],
  ['荣华富贵', 'róng huá fù guì', 'nabobism'],
  ['富贵荣华', 'fù guì róng huá', 'riches and honour'],
  ['如火如荼', 'rú huǒ rú tú', 'like a raging fire'],
  ['如释重负', 'rú shì zhòng fù', 'as if relieved of a heavy load'],
  ['三思而行', 'sān sī ér xíng', 'think twice'],
  ['僧多粥少', 'sēng duō zhōu shǎo', 'not enough to satisfy everyone'],
  ['杀鸡取卵', 'shā jī qū luǎn', 'kill a chicken to steal its eggs'],
  ['舍己为人', 'shě jǐ wèi rén', 'to sacrifice oneself for the sake of others'],
  ['事半功倍', 'shì bàn gōng bèi', 'get twice the result with half the effort'],
  ['事倍功半', 'shì bèi gōng bàn', 'get half the result with twice the effort'],
  ['视死如归', 'shì sǐ rú guī', 'face death unflinchingly'],
  ['手不释卷', 'shǒu bù shì juàn', 'very diligent very studious'],
  ['守口如瓶', 'shǒu kǒu rú píng', "keep one's mouth shut"],
  ['守望相助', 'shǒu wàng xiāng zhù', 'help each other'],
  ['守株待兔', 'shǒu zhū dài tù', 'wait for windfalls'],
  ['熟能生巧', 'shóu néng shēng qiǎo', 'practice makes perfect'],
  ['束手无策', 'shù shǒu wú cè', 'nail-biting'],
  ['水到渠成', 'shuǐ dào qú chéng', 'success will come when conditions are ripe'],
  ['水落石出', 'shuǐ luo shí chū', 'everything comes to light everything becomes obvious'],
  ['顺手牵羊', 'shùn shǒu qiān yáng', 'pick up sth. on the sly snitch'],
  ['司空见惯', 'sī kōng jiàn guàn', 'a common occurrence'],
  ['似是而非', 'sì shì ér fēi', 'appeared right but was wrong'],
  ['随遇而安', 'suí yù ér ān', 'make the best of things take things as they come'],
  ['滔滔不绝', 'tāo tāo bù jué', 'gushing non-stopping'],
  ['口若悬河', 'kǒu ruo xuán hé', 'eloquent speak volubly'],
  ['提心吊胆', 'tí xīn diào dǎn', 'be in fear of in fear and trembling'],
  ['挑拨离间', 'tiāo bō lí jiān', 'make mischief play sb. off against one another'],
  ['铤而走险', 'tǐng ér zǒu xiǎn', 'risk danger in desperation'],
  ['同甘共苦', 'tóng gān gòng kǔ', 'share happiness and woe'],
  ['同归于尽', 'tóng guī yú jìn', 'perish together'],
  ['同流合污', 'tóng liú hé wū', 'associate with an evil person'],
  ['同舟共济', 'tóng zhōu gòng jì', "we're in the same boat"],
  ['投机取巧', 'tóu jī qū qiǎo', 'opportunistic'],
  ['徒劳无功', 'tú láo wú gōng', "be a fool for one's pains"],
  ['推陈出新', 'tuī chén chū xīn', 'get rid of the stale and bring forth the fresh'],
  ['望尘莫及', 'wàng chén mo jí', 'too far behind to catch up with'],
  ['忘恩负义', 'wàng ēn fù yì', 'ungratefulness'],
  ['为非作歹', 'wèi fēi zuo dǎi', 'commit crimes do evil'],
  ['未雨绸缪', 'wèi yǔ chóu móu', 'prepare for a rainy day plan ahead'],
  ['温故知新', 'wēn gù zhī xīn', 'gain new insights through reviewing old material'],
  ['无病呻吟', 'wú bìng shēn yín', 'make a fuss about an imaginary illness'],
  ['无动于衷', 'wú dòng yú zhōng', 'sit by and do nothing nonchalance'],
  ['无微不至', 'wú wēi bù zhì', 'very carefully and meticulously'],
  ['五体投地', 'wǔ tǐ tóu dì', 'extremely admire'],
  ['息事宁人', 'xī shì zhù rén', 'make concessions to avoid trouble'],
  ['相安无事', 'xiāng ān wú shì', 'live in peace with each other'],
  ['相辅相成', 'xiāng fǔ xiāng chéng', 'to supplement each other'],
  ['心灰意懒', 'xīn huī yì lǎn', 'dejected depressed downhearted'],
  ['心旷神怡', 'xīn kuàng shén yí', 'relaxed and happy'],
  ['欣欣向荣', 'xīn xīn xiàng róng', 'flourishing prosperous thriving'],
  ['信口开河', 'xìn kǒu kāi hé', 'run off at the mouth'],
  ['信口雌黄', 'xìn kǒu cí huáng', 'make irresponsible remarks'],
  ['兴高采烈', 'xīng gāo cǎi liè', 'in great form in high spirits'],
  ['胸有成竹', 'xiōng yǒu chéng zhú', "have a card up one's sleeve have a well-thought-out plan"],
  ['袖手旁观', 'xiù shǒu páng guān', 'look on with folded arms sit by'],
  ['栩栩如生', 'xǔ xǔ rú shēng', 'lifelike'],
  ['悬崖勒马', 'xuán yá lè mǎ', 'wake up to and avoid danger at the last moment'],
  ['削足适履', 'xuē zú shì lǚ', 'act in a Procrustean way cut the feet to fit the shoes'],
  ['寻根究底', 'xún gēn jiù dǐ', 'inquire deeply into'],
  ['循循善诱', 'xún xún shàn yòu', 'be good at teaching'],
  ['鸦雀无声', 'yā què wú shēng', 'silence reigns'],
  ['雅俗共赏', 'yǎ sú gòng shǎng', 'suit both refined and popular tastes'],
  ['言行一致', 'yán xíng yī zhì', 'practice what you preach'],
  ['养尊处优', 'yǎng zūn chù yōu', 'do oneself proud'],
  ['摇摇欲坠', 'yáo yáo yù zhuì', 'hang by a thread to shake'],
  ['一败涂地', 'yī bài tú dì', 'bite the ground hunt grass'],
  ['一帆风顺', 'yī fān fēng shùn', 'plain sailing very smoothly'],
  ['一见如故', 'yī jiàn rú gù', 'feel like old friends at the first meeting'],
  ['一举两得', 'yī jǔ liǎng dé', 'kill two birds with one stone'],
  ['一箭双雕', 'yī jiàn shuāng diāo', 'kill two birds with one stone'],
  ['一蹶不振', 'yī jué bù zhèn', 'cannot recover after a setback'],
  ['一劳永逸', 'yī láo yǒng yì', 'get sth. done once and for ever'],
  ['一落千丈', 'yī luo qiān zhàng', 'suffer a disastrous decline'],
  ['一毛不拔', 'yī máo bù bá', 'miserly very stingy'],
  ['一目瞭然', 'yī mù liǎo rán', 'be clear at a glance'],
  ['一暴十寒', 'yī bào shí hán', 'daily effort is needed learn and grow'],
  ['一视同仁', 'yī shì tóng rén', 'treat equally without discrimination'],
  ['一事无成', 'yī shì wú chéng', 'accomplish nothing'],
  ['一网打尽', 'yī wǎng dǎ jìn', 'catch the whole lot in an action'],
  ['一意孤行', 'yī yì gū xíng', "go one's own way take one's own course"],
  ['一针见血', 'yī zhēn jiàn xiě', 'hit the nail on the head to get to the point'],
  ['一知半解', 'yī zhī bàn jiě', 'have little knowledge and no comprehension'],
  ['以卵击石', 'yǐ luǎn jí shí', 'kick against the pricks throw straws against the wind'],
  ['以身作则', 'yǐ shēn zuò zé', 'set a good example'],
  ['以牙还牙', 'yǐ yá huán yá', 'give as good as one gets a tooth for a tooth (retaliation)'],
  ['易如反掌', 'yì rú fǎn zhǎng', "as easy as turning one's hand over"],
  ['异想天开', 'yì xiǎng tiān kāi', 'let imagination run wild whimsicality'],
  ['饮水思源', 'yǐn shuǐ sī yuán', "never forget where one's happiness comes from"],
  ['迎刃而解', 'yíng rèn ér jiě', 'be readily solved'],
  ['应接不暇', 'yìng jiē bù xiá', 'have too many visitors or business to deal with'],
  ['优柔寡断', 'yōu róu guǎ duàn', 'indecision irresolution yea and nay'],
  ['游手好闲', 'yóu shǒu hǎo xián', 'to procrastinate to dawdle shilly-shally'],
  ['有目共睹', 'yǒu mù gòng dǔ', 'be obvious to all'],
  ['有勇无谋', 'yǒu yǒng wú móu', 'foolhardiness'],
  ['与日俱增', 'yǔ rì jù zēng', 'grow day by day increase steadily'],
  ['再接再厉', 'zài jiē zài lì', 'make persistent efforts'],
  ['真知灼见', 'zhēn zhī zhuó jiàn', 'penetrating judgment'],
  ['蒸蒸日上', 'zhēng zhēng rì shàng', 'becoming more prosperous each passing day flourishing'],
  ['执迷不悟', 'zhí mí bù wù', 'come to their senses'],
  ['趾高气扬', 'zhǐ gāo qì yáng', "hold one's head high lift up one's horn"],
  ['纸上谈兵', 'zhǐ shàng tán bīng', 'be an armchair strategist engage in idle theorizing'],
  ['志同道合', 'zhì tóng dào hé', 'to have a common objective in the same camp'],
  ['置之不理', 'zhì zhī bù lǐ', "put sth. on one side turn one's back upon"],
  ['忠言逆耳', 'zhōng yán nì ěr', 'good advice is harsh to the ear'],
  ['装聋作哑', 'zhuāng lóng zuò yā', 'to act deaf and dumb'],
  ['自暴自弃', 'zì bào zì qì', 'desperateness abandonment'],
  ['自力更生', 'zì lì gèng shēng', 'self-reliance self-dependence'],
  ['自投罗网', 'zì tóu luó wǎng', 'hurl oneself willingly into the net'],
  ['自相矛盾', 'zì xiāng máo dùn', 'self-contradiction contradict oneself'],
  ['坐井观天', 'zuò jǐng guān tiān', 'have a very narrow view'],
  ['坐享其成', 'zuò xiǎng qí chéng', 'reap where one has not sown']
]
